### ISSUE TITLE
installation of package ‘eDMA’ had non-zero exit status for Mac

### ISSUE THREAD

**Issue by lotusfr** [LeopoldoCatania/eDMA#1]
I try to install eDMA via
install.packages("eDMA")
but it doesn't work.

```
Estimate.cpp:4:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
make: *** [Estimate.o] Error 1
ERROR: compilation failed for package ‘eDMA’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/eDMA’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/eDMA’
Warning in install.packages :
  installation of package ‘eDMA’ had non-zero exit status
```

My session information is as follows
```

R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.1 (Sierra)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.2-7.1

loaded via a namespace (and not attached):
[1] tools_3.3.1     rpart_4.1-10    grid_3.3.1      lattice_0.20-34
```

Thank you

**Comment by LeopoldoCatania** [comment]
OpenMP is problematic with OS X, please see [here](http://stackoverflow.com/questions/20340117/omp-h-library-isnt-found-in-the-gcc-version-4-2-1-in-mavericks) and [here](http://stackoverflow.com/questions/25990296/how-to-include-omp-h-in-os-x) . 

The new version 0.1.3 of eDMA  (available from today on [CRAN ](https://cran.r-project.org/web/packages/eDMA/index.html) and on [GitHub](https://github.com/LeopoldoCatania/eDMA)) supports systems without OpenMP. However, OpenMP is required for parallel computing.

Once you will have OpenMP available on your system. Please reinstall the eDMA package to enjoy parallel computing.

Best,
Leopoldo.

**Comment by lotusfr** [comment]
Thank you so much! I installed the new version. It works:)
